code_style_task:
  container:
    dockerfile: .ci/Dockerfile
    cpu: 8
    memory: 16G
  matrix:
    - name: test+format
#      install_script:
#        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
#        - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main"
#        - sudo apt-get update
#        - sudo apt-get install -y --allow-unauthenticated clang-format-7
      format_script: script/format.sh
    - name: analyze
      script:
        - pub global activate tuneup
        - flutter packages get
        - pub global run tuneup check

android_task:
  container:
    dockerfile: .ci/Dockerfile
    cpu: 8
    memory: 16G
  build_script:
    - cd example && flutter build apk --release

ios_task:
  osx_instance:
    image: mojave-flutter
  build_script:
    - pod repo update
    - cd example && flutter build ios --release --no-codesign
